# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-13 18:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Access_to_server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Access_to_service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Access_to_switches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('privilege', models.CharField(max_length=50)),
                ('machine', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('user', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Server')),
            ],
        ),
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='personnel_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.Personnel'),
        ),
        migrations.AddField(
            model_name='access_to_switches',
            name='switches_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Switch'),
        ),
        migrations.AddField(
            model_name='access_to_switches',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Personnel'),
        ),
        migrations.AddField(
            model_name='access_to_service',
            name='service_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Service'),
        ),
        migrations.AddField(
            model_name='access_to_service',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Personnel'),
        ),
        migrations.AddField(
            model_name='access_to_server',
            name='server_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Server'),
        ),
        migrations.AddField(
            model_name='access_to_server',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Personnel'),
        ),
        migrations.AlterUniqueTogether(
            name='access_to_switches',
            unique_together=set([('username', 'switches_ID')]),
        ),
        migrations.AlterUniqueTogether(
            name='access_to_service',
            unique_together=set([('username', 'service_ID')]),
        ),
        migrations.AlterUniqueTogether(
            name='access_to_server',
            unique_together=set([('username', 'server_ID')]),
        ),
    ]
