# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-13 16:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('privilege', models.CharField(max_length=50)),
                ('machine', models.CharField(max_length=50, primary_key=True)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('user', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Servers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Switches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='user',
        ),
        migrations.CreateModel(
            name='Access_to_server',
            fields=[
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='web.Personnel')),
                ('server_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, to='web.Servers')),
            ],
        ),
        migrations.CreateModel(
            name='Access_to_service',
            fields=[
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='web.Personnel')),
                ('service_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, to='web.Services')),
            ],
        ),
        migrations.CreateModel(
            name='Access_to_switches',
            fields=[
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='web.Personnel')),
                ('switches_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, to='web.Switches')),
            ],
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.AddField(
            model_name='services',
            name='server_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Servers'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='personnel_ID',
            field=models.ForeignKey(default='Out-of-management', on_delete=django.db.models.deletion.SET_DEFAULT, to='web.Personnel'),
        ),
    ]
