# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-15 04:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='access_to_server',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='access_to_server',
            name='server_id',
        ),
        migrations.RemoveField(
            model_name='access_to_server',
            name='username',
        ),
        migrations.AlterUniqueTogether(
            name='access_to_switch',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='access_to_switch',
            name='switch_id',
        ),
        migrations.RemoveField(
            model_name='access_to_switch',
            name='username',
        ),
        migrations.RenameField(
            model_name='access_to_service',
            old_name='service_id',
            new_name='service_name',
        ),
        migrations.RenameField(
            model_name='interface',
            old_name='server_id',
            new_name='server_name',
        ),
        migrations.RenameField(
            model_name='interface',
            old_name='port_id',
            new_name='switch_port',
        ),
        migrations.RenameField(
            model_name='port',
            old_name='switch_id',
            new_name='switch_name',
        ),
        migrations.RenameField(
            model_name='server_account',
            old_name='server_id',
            new_name='server_name',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='port_id',
            new_name='port',
        ),
        migrations.RenameField(
            model_name='switch',
            old_name='brand_and_model',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='switch_account',
            old_name='switch_id',
            new_name='switch_name',
        ),
        migrations.RenameField(
            model_name='vlan_to_interface',
            old_name='interface_id',
            new_name='interface_name',
        ),
        migrations.RemoveField(
            model_name='server',
            name='brand_and_model',
        ),
        migrations.RemoveField(
            model_name='service',
            name='interface_id',
        ),
        migrations.RemoveField(
            model_name='service',
            name='server_id',
        ),
        migrations.AddField(
            model_name='interface',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='name',
            field=models.CharField(default=456456, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='interface_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Interface'),
        ),
        migrations.AddField(
            model_name='service',
            name='server_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Server'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='name',
            field=models.CharField(default=312315, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personnel',
            name='user',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='access_to_service',
            unique_together=set([('username', 'service_name')]),
        ),
        migrations.AlterUniqueTogether(
            name='vlan_to_interface',
            unique_together=set([('vlan_id', 'interface_name')]),
        ),
        migrations.DeleteModel(
            name='Access_to_server',
        ),
        migrations.DeleteModel(
            name='Access_to_switch',
        ),
    ]
