# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-18 18:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20180115_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server_account',
            old_name='personnel_id',
            new_name='personnel',
        ),
        migrations.RenameField(
            model_name='switch_account',
            old_name='personnel_id',
            new_name='personnel',
        ),
    ]
